### ISSUE TITLE
There is no online EDN pretty-printer

### ISSUE THREAD

**Issue by oakmac** [comamitc/pretty-print.net#1]
[EDN](https://github.com/edn-format/edn) is a powerful data interchange format commonly used with Clojure and ClojureScript programs. It also doubles as a literal representation of most Clojure data structures, which are often printed to a REPL or console environment for debugging purposes.

Clojure core comes with [clojure.pprint](https://clojure.github.io/clojure/clojure.pprint-api.html) - which is a library to format Clojure code (and thus EDN) in a human-readable fashion.

As of January 2015, there are numerous online services to pretty print various data interchange formats (JSON, YAML, XML, etc), but there is no online service for printing an EDN string.

This project aims to build such a service and improve the usability of working with EDN data.

**Comment by comamitc** [comment]
http://pretty-print.net/

**Comment by oakmac** [comment]
Great work :)
