### ISSUE TITLE
weird formatting behavior

### ISSUE THREAD

**Issue by comamitc** [comamitc/pretty-print.net#19]
```
{:users [{:name "Dan", :age 23}
                  {:name "Sam", :gender :female}]
          :aliases {"Dan" ["Dante" "Daniel"]
                    "Sam" ["Samantha", "Samoth"]}}
```

Gets output as 

```
{:users [{:name "Dan", :age 23} {:name "Sam", :gender :female}],
 :aliases {"Dan" ["Dante" "Daniel"], "Sam" ["Samantha" "Samoth"]}}
```

**Comment by comamitc** [comment]
This can be fixed by setting "right-margin". This screams that we need "settings" in the UI of pretty-print.net.

By setting it to 40 I got this:

```
{:users
 [{:name "Dan", :age 23}
  {:name "Sam", :gender :female}],
 :aliases
 {"Dan" ["Dante" "Daniel"],
  "Sam" ["Samantha" "Samoth"]}}
```

**Comment by comamitc** [comment]
Open #20 to track enhancement progress.

**Comment by boxed** [comment]
That later one isn't significantly better. The problem seems to me to be that it doesn't have a concept of map literal elements being alternating keys and values and handling that differently than just if it was a list of stuff.

**Comment by comamitc** [comment]
I agree with your assessment. While adding the formatter's settings into the UI of pretty-print might help this a little (arguably so) the underlying problem seems to be with the `clojure.pprint` library in how it deals with these objects. I will open an issue there for this and see if we can get some traction.

**Comment by comamitc** [comment]
This should be solved in #34

**Comment by comamitc** [comment]
#34 now produces this output for the example input:

``` clj
{:users [{:name "Dan", :age 23}
         {:name "Sam", :gender :female}]
 :aliases {"Dan" ["Dante" "Daniel"]
           "Sam" ["Samantha", "Samoth"]}}
```

Based on [`cljfmt`](https://github.com/weavejester/cljfmt).

**Comment by comamitc** [comment]
Closing this based on #34 & #44.
