### ISSUE TITLE
Works for Hiccup Data?

### ISSUE THREAD

**Issue by Quasaur** [comamitc/pretty-print.net#27]
Your online masterpiece (http://pretty-print.net/#/format/edn) seems to have done an excellent job of pretty-printing my Hiccup data; i just wanted to confirm with you that you intended it for that kind of use...?
I would also be interested in the data size limit (the biggest i've submitted is 36,479 characters).

**Comment by oakmac** [comment]
Absolutely :) [Issue #1](https://github.com/comamitc/pretty-print.net/issues/1)

**Comment by comamitc** [comment]
We don't enforce a size limit as we just haven't found a use case for enforcing one yet.  Let us know if you have any other questions or concerns.

**Comment by Quasaur** [comment]
Thanks!
