### ISSUE TITLE
Looking for new owner / host

### ISSUE THREAD

**Issue by comamitc** [comamitc/pretty-print.net#33]
http://pretty-print.net/ is no longer functioning due to me shutting down the JVM that could no longer run on my server due to memory constraints. I am, at this time, unable to keep up with this project and dedicate the resources to keep it running.

I'll be departing with the project with or without an owner by Feb 28th, 2016.

**Comment by oakmac** [comment]
How much traffic does the site get? Would it be possible to run it on a "free tier" hosting somewhere?

**Comment by oakmac** [comment]
Also - is the JVM required now that CLJS has pretty-print and is self-hosting?

**Comment by comamitc** [comment]
You could probably swap over to the CLJS version of pretty-printer with potentially the following caveat:
- I had to [fork `tools.reader`](https://github.com/comamitc/clj-beautify) and add logic in to preserve comments and macros during the formatting process. I am not sure how or if the CLJS pretty printer handles these cases (Probably a question for @shaunlebron) 

I'm unsure about traffic. It wasn't much at all at the launch of the project but I stopped recording google analytics after some time (it was tied to another _corporate_ account and I never switched it over).

**Comment by oakmac** [comment]
I am going to find some way for this project to live on. As far as I know this is the only way to see EDN data pretty-printed on the web!

**Comment by comamitc** [comment]
So I've spent some time trying to make it so that pretty-print.net deploys itself on master changes. 

This is a perfect example (and maybe a calling for migrating to CLJS) of how resource intensive the build process is. `lein` cannot be run without setting a maximum `jvm` memory settings or it runs into this during normal compilation:

``` sh
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000ef585000, 33767424, 0) failed; error='Cannot allocate memory' (errno=12)
```

I've made these changes to ensure it builds.  Because a 512mb server is constrained with this process; I shut down all `jvm` processes before deploying to server.  When deployment is in process the server will remain down between 2 - 3 minutes.

Closing this for now. Opening an issue to port to clojurescript.

**Comment by oakmac** [comment]
:+1: to migrating this to CLJS

**Comment by shaunlebron** [comment]
> I had to fork tools.reader and add logic in to preserve comments and macros during the formatting process. I am not sure how or if the CLJS pretty printer handles these cases

nah, cljs.pprint is just a straight port of clojure.pprint
