### ISSUE TITLE
Add gitter-chat

### ISSUE THREAD

**Issue by comamitc** [comamitc/pretty-print.net#36]
Seems like a good place to allow people to ask questions without opening issues.

**Comment by oakmac** [comment]
:-1:

What is the benefit of someone asking a question without opening an issue?

Issues provide history, asynchronous communication, and "one source of truth" for the project.

**Comment by shaunlebron** [comment]
people are more likely to ask a question in chat, which can lead to formal issues being filed after some details are discussed.  I've seen this happen in cljs and parinfer projects.

**Comment by comamitc** [comment]
I'm not strongly opinionated either way, but the `#clojurians` slack definitely gave me the idea. It's strongly suggested questions and even bug reports go through the slack before making their way to JIRA.

**Comment by comamitc** [comment]
Not important.
