### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by kernelp4nic** [comamitc/pretty-print.net#39]
http://pretty-print.net/ is reporting bad gw when formatting:

![2016-02-16_15-25-56](https://cloud.githubusercontent.com/assets/519481/13086291/62549e14-d4c1-11e5-8977-fb7ba70e7998.png)

**Comment by comamitc** [comment]
Memory issue on server

`nohup java -jar target/pp-jvm-server-0.1.0-standalone.jar &`

I've restarted it. Thanks for the notification.
