### ISSUE TITLE
Reader only supports one object for Clojure & EDN

### ISSUE THREAD

**Issue by comamitc** [comamitc/pretty-print.net#4]
potential fix: 

http://stackoverflow.com/questions/6840425/with-clojure-read-read-string-function-how-do-i-read-in-a-clj-file-to-a-list-o

**Comment by shaunlebron** [comment]
yeah, `read-string` is weird that way. But if you look at [what it's doing](https://github.com/clojure/tools.reader/blob/e317cf2f3226a94ce6c595b9b8679303726b2594/src/main/clojure/clojure/tools/reader.clj#L790), it creates a "reader" and calls `read` on it once.  You'll have to call `read` multiple times on that reader until you get the EOF object or exception back.
