### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by ryanbaldwin** [comamitc/pretty-print.net#40]
pretty-print.net is currently down. The UI loads, but the underlying functionality is busted. Console says it's a 502 Bad Gateway. Sounds like your backing service is down.

**Comment by comamitc** [comment]
Thanks, I added an uptime robot to this service since I cannot reliably count on the JVM service to not max out my small hosting box.

Closed via 72a71f390e446f6bcac7b3548e56e52cb3c3470c
