### ISSUE TITLE
Syntax highlighting for the formatted output

### ISSUE THREAD

**Issue by comamitc** [comamitc/pretty-print.net#9]
http://codemirror.net/

```
It is the editor used in the dev tools for both Firefox and Chrome, Light Table, Adobe Brackets, Bitbucket, and many other projects.
```

**Comment by NPrescott** [comment]
Some options for syntax highlighting include:
- [Pygments](http://pygments.org/) (server side python)
- [SyntaxHighlighter](https://github.com/syntaxhighlighter/syntaxhighlighter) (client side javascript), would require a [third party brush](http://travis-whitton.blogspot.com/2009/06/syntaxhighlighter-for-clojure.html) for Clojure or writing your own syntax which appears relatively easy

Are you interested in a full-blown editor like codemirror or simple (dumb) syntax highlighting? 

It seems like the obvious thing to do for a "service" such as this is to output the prettified content to a `<pre>` tag (like [JSON Pretty Print](http://jsonprettyprint.com/)), if for no other reason than semantics, but I haven't dug into check what is being done currently. If that is the case, then it significantly limits the options for syntax highlighting (server side highlighting seems to uniformly be a CSS hack like Pygments).

**Comment by comamitc** [comment]
The idea here is that the formatted string is sent back to the client and represented in the text box, instead of a separate element or page.  So having the syntax highlighting in inside of the text box is necessary.

Additional, one other feature that something like Code Mirror would help us accomplish is highlighting which line and column has a respective syntax error in the case of _beautifying_ failure.

**Comment by comamitc** [comment]
Using CodeMirror in #44.

**Comment by shaunlebron** [comment]
😍 so pretty

<img width="1083" alt="screen shot 2016-08-16 at 9 43 15 pm" src="https://cloud.githubusercontent.com/assets/116838/17722786/78fe1e38-63fa-11e6-991d-7c35a001c479.png">
